name: Flutter Test & Quality

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: '3.24.5'

jobs:
  quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Analyze project source
      run: flutter analyze
      
    - name: Check formatting
      run: dart format --set-exit-if-changed .
      
    - name: Check for unused imports
      run: |
        dart pub global activate dart_code_metrics
        dart pub global run dart_code_metrics:metrics analyze lib
      continue-on-error: true

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run unit tests
      run: flutter test --coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run integration tests
      run: flutter test integration_test/
      continue-on-error: true

  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run performance tests
      run: flutter test test/performance/
      continue-on-error: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Audit dependencies
      run: flutter pub deps --style=tree
      
    - name: Check for known vulnerabilities
      run: |
        # Check pubspec.lock for known vulnerable packages
        if grep -i "vulnerability\|security\|cve" pubspec.lock; then
          echo "⚠️ Potential security issues found in dependencies"
          exit 1
        fi
      continue-on-error: true

  test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: [quality-check, unit-test, integration-test, performance-test, security-audit]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate test report
      run: |
        echo "## Test Results Summary" >> test-report.md
        echo "### Quality Check: ${{ needs.quality-check.result }}" >> test-report.md
        echo "### Unit Tests: ${{ needs.unit-test.result }}" >> test-report.md
        echo "### Integration Tests: ${{ needs.integration-test.result }}" >> test-report.md
        echo "### Performance Tests: ${{ needs.performance-test.result }}" >> test-report.md
        echo "### Security Audit: ${{ needs.security-audit.result }}" >> test-report.md
        
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test-report.md 