name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: '3.24.5'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Analyze project source
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Run integration tests
      run: flutter test integration_test/
      continue-on-error: true
      
    - name: Check code coverage
      run: flutter test --coverage
      continue-on-error: true

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: habitflow-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build iOS
      run: flutter build ios --release --no-codesign
      
    - name: Upload iOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: habitflow-ios
        path: build/ios/archive/

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Upload Web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: habitflow-web
        path: build/web/

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run security audit
      run: flutter pub deps --style=tree
      
    - name: Check for vulnerabilities
      run: |
        if flutter pub deps --style=tree | grep -i "vulnerability\|security\|cve"; then
          echo "Security vulnerabilities found!"
          exit 1
        fi
      continue-on-error: true

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: [test, build-web]
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Web build
      uses: actions/download-artifact@v4
      with:
        name: habitflow-web
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        destination_dir: preview/${{ github.event.number }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, build-android, build-ios, build-web]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: habitflow-apk
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
        tag_name: v${{ github.run_number }}
        name: HabitFlow v${{ github.run_number }}
        body: |
          ## What's Changed
          
          ### 🚀 New Features
          - Enhanced notification system with multi-layer reminders
          - Improved habit tracking and statistics
          - Modern glassmorphism UI design
          
          ### 🐛 Bug Fixes
          - Fixed notification scheduling issues
          - Improved activity tracking accuracy
          - Resolved UI alignment problems
          
          ### 📱 Platform Support
          - Android APK included
          - iOS build available
          - Web version supported
          
          ## Installation
          
          ### Android
          Download the APK file and install on your Android device.
          
          ### iOS
          Build from source using Xcode.
          
          ### Web
          Visit the deployed web version.
          
          ## System Requirements
          
          - Android: API 21+ (Android 5.0+)
          - iOS: iOS 12.0+
          - Web: Modern browser with JavaScript enabled
          
          ## Features
          
          - ✅ Habit tracking with reminders
          - ✅ Statistics and insights
          - ✅ Modern UI with glassmorphism
          - ✅ Multi-platform support
          - ✅ Offline functionality
          - ✅ Data persistence
          
          ## Contributing
          
          See [CONTRIBUTING.md](CONTRIBUTING.md) for details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    needs: [test, build-android, build-ios, build-web]
    if: always()
    
    steps:
    - name: Notify on Success
      if: success()
      run: |
        echo "✅ All checks passed successfully!"
        echo "Build completed for commit: ${{ github.sha }}"
        
    - name: Notify on Failure
      if: failure()
      run: |
        echo "❌ Build failed for commit: ${{ github.sha }}"
        echo "Please check the logs for details." 