name: Flutter Android Release Build

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Trigger only on pushes to main

permissions:
  contents: write  # Required to create GitHub Release and upload assets

jobs:
  build:
    name: Build and Release Split APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # Set your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs with ABI splits
        run: flutter build apk --split-per-abi

      - name: Upload APKs to GitHub Actions artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-apks
          path: build/app/outputs/flutter-apk/

      - name: Create GitHub Release and upload APKs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.0  # Change version tag as needed
          name: Release v1.1.0
          files: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
